#include <__expected/unexpected.h>
#include <glaze/glaze.hpp>
#include <cpr/cpr.h>
#include "cpr/response.h"
#include "sll.hpp"

LL_NAMESPACE_BEGIN

enum ResponseStatus {
    RESPONSE_STATUS_CONTINUE = 100,
    RESPONSE_STATUS_SWITCHING_PROTOCOLS = 101,
    RESPONSE_STATUS_PROCESSING = 102,
    RESPONSE_STATUS_EARLY_HINTS = 103,
    RESPONSE_STATUS_OK = 200,
    RESPONSE_STATUS_CREATED = 201,
    RESPONSE_STATUS_ACCEPTED = 202,
    RESPONSE_STATUS_NON_AUTHORITATIVE_INFORMATION = 203,
    RESPONSE_STATUS_NO_CONTENT = 204,
    RESPONSE_STATUS_RESET_CONTENT = 205,
    RESPONSE_STATUS_PARTIAL_CONTENT = 206,
    RESPONSE_STATUS_MULTI_STATUS = 207,
    RESPONSE_STATUS_ALREADY_REPORTED = 208,
    RESPONSE_STATUS_THIS_IS_FINE__APACHE_WEB_SERVER_ = 218,
    RESPONSE_STATUS_IM_USED = 226,
    RESPONSE_STATUS_MULTIPLE_CHOICES = 300,
    RESPONSE_STATUS_MOVED_PERMANENTLY = 301,
    RESPONSE_STATUS_FOUND = 302,
    RESPONSE_STATUS_SEE_OTHER = 303,
    RESPONSE_STATUS_NOT_MODIFIED = 304,
    RESPONSE_STATUS_SWITCH_PROXY = 306,
    RESPONSE_STATUS_TEMPORARY_REDIRECT = 307,
    RESPONSE_STATUS_RESUME_INCOMPLETE = 308,
    RESPONSE_STATUS_BAD_REQUEST = 400,
    RESPONSE_STATUS_UNAUTHORIZED = 401,
    RESPONSE_STATUS_PAYMENT_REQUIRED = 402,
    RESPONSE_STATUS_FORBIDDEN = 403,
    RESPONSE_STATUS_NOT_FOUND = 404,
    RESPONSE_STATUS_METHOD_NOT_ALLOWED = 405,
    RESPONSE_STATUS_NOT_ACCEPTABLE = 406,
    RESPONSE_STATUS_PROXY_AUTHENTICATION_REQUIRED = 407,
    RESPONSE_STATUS_REQUEST_TIMEOUT = 408,
    RESPONSE_STATUS_CONFLICT = 409,
    RESPONSE_STATUS_GONE = 410,
    RESPONSE_STATUS_LENGTH_REQUIRED = 411,
    RESPONSE_STATUS_PRECONDITION_FAILED = 412,
    RESPONSE_STATUS_REQUEST_ENTITY_TOO_LARGE = 413,
    RESPONSE_STATUS_REQUEST_URI_TOO_LONG = 414,
    RESPONSE_STATUS_UNSUPPORTED_MEDIA_TYPE = 415,
    RESPONSE_STATUS_REQUESTED_RANGE_NOT_SATISFIABLE = 416,
    RESPONSE_STATUS_EXPECTATION_FAILED = 417,
    RESPONSE_STATUS_IM_A_TEAPOT = 418,
    RESPONSE_STATUS_PAGE_EXPIRED_LARAVEL_FRAMEWORK = 419,
    RESPONSE_STATUS_METHOD_FAILURE_SPRING_FRAMEWORK = 420,
    RESPONSE_STATUS_MISDIRECTED_REQUEST = 421,
    RESPONSE_STATUS_UNPROCESSABLE_ENTITY = 422,
    RESPONSE_STATUS_LOCKED = 423,
    RESPONSE_STATUS_FAILED_DEPENDENCY = 424,
    RESPONSE_STATUS_UPGRADE_REQUIRED = 426,
    RESPONSE_STATUS_PRECONDITION_REQUIRED = 428,
    RESPONSE_STATUS_TOO_MANY_REQUESTS = 429,
    RESPONSE_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
    RESPONSE_STATUS_LOGIN_TIME_OUT = 440,
    RESPONSE_STATUS_CONNECTION_CLOSED_WITHOUT_RESPONSE = 444,
    RESPONSE_STATUS_RETRY_WITH = 449,
    RESPONSE_STATUS_BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS = 450,
    RESPONSE_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS = 451,
    RESPONSE_STATUS_REQUEST_HEADER_TOO_LARGE = 494,
    RESPONSE_STATUS_SSL_CERTIFICATE_ERROR = 495,
    RESPONSE_STATUS_SSL_CERTIFICATE_REQUIRED = 496,
    RESPONSE_STATUS_HTTP_REQUEST_SENT_TO_HTTPS_PORT = 497,
    RESPONSE_STATUS_INVALID_TOKEN_ESRI = 498,
    RESPONSE_STATUS_CLIENT_CLOSED_REQUEST = 499,
    RESPONSE_STATUS_INTERNAL_SERVER_ERROR = 500,
    RESPONSE_STATUS_NOT_IMPLEMENTED = 501,
    RESPONSE_STATUS_BAD_GATEWAY = 502,
    RESPONSE_STATUS_SERVICE_UNAVAILABLE = 503,
    RESPONSE_STATUS_GATEWAY_TIMEOUT = 504,
    RESPONSE_STATUS_HTTP_VERSION_NOT_SUPPORTED = 505,
    RESPONSE_STATUS_VARIANT_ALSO_NEGOTIATES = 506,
    RESPONSE_STATUS_INSUFFICIENT_STORAGE = 507,
    RESPONSE_STATUS_LOOP_DETECTED = 508,
    RESPONSE_STATUS_BANDWIDTH_LIMIT_EXCEEDED = 509,
    RESPONSE_STATUS_NOT_EXTENDED = 510,
    RESPONSE_STATUS_NETWORK_AUTHENTICATION_REQUIRED = 511,
    RESPONSE_STATUS_UNKNOWN_ERROR = 520,
    RESPONSE_STATUS_WEB_SERVER_IS_DOWN = 521,
    RESPONSE_STATUS_CONNECTION_TIMED_OUT = 522,
    RESPONSE_STATUS_ORIGIN_IS_UNREACHABLE = 523,
    RESPONSE_STATUS_A_TIMEOUT_OCCURRED = 524,
    RESPONSE_STATUS_SSL_HANDSHAKE_FAILED = 525,
    RESPONSE_STATUS_INVALID_SSL_CERTIFICATE = 526,
    RESPONSE_STATUS_RAILGUN_LISTENER_TO_ORIGIN_ERROR = 527,
    RESPONSE_STATUS_ORIGIN_DNS_ERROR = 530,
    RESPONSE_STATUS_NETWORK_READ_TIMEOUT_ERROR = 598
};
template<typename T> using ResponseValue = std::expected<T, ResponseStatus>;

static inline ResponseValue<cpr::Response> rozfetch_get_response(const char *url){
    const cpr::Response response = cpr::Get(cpr::Url{url});
    
    if(response.status_code < 200 || response.status_code > 299){
        return std::unexpected(static_cast<ResponseStatus>(response.status_code));
    }
    return response;
}

template<class T> static inline ResponseValue<T> rozfetch_get_json(const char *url){
    const ResponseValue<cpr::Response> response = rozfetch_get_response(url);
    if(!response.has_value()) return std::unexpected(response.error());
    T parsed;
    const auto json_err = glz::read_json<T>(parsed, response.value().text);

    if(json_err) {
        LL_LOG_ERROR("Failed to read JSON: {}", glz::format_error(json_err));
        return std::unexpected(ResponseStatus::RESPONSE_STATUS_UNKNOWN_ERROR);
    }
    return parsed;
}
// static ResponseValue<std::string> rozfetch_get_text(const char *url){
//     const ResponseValue<cpr::Response> response = rozfetch_get_response(url);
//     if(!response.has_value()) return response.error();
//     return response.value().text;
// }
LL_NAMESPACE_END